Meter/Meter/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from Reading.views import DataViewSet,MeterViewSet
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'data',DataViewSet)
router.register(r'meter',MeterViewSet)


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^reading/',include('Reading.urls')),
    # url(r'^api-auth/', include('rest_framework.urls')),
]
urlpatterns += router.urls

Meter/Reading/urls.py
from django.conf.urls import url
from . import views

app_name="meter"

urlpatterns = [
	url(r'^$',views.IndexView.as_view(),name='index'),
	url(r'^(?P<pk>[\w]+)/$',views.DetailView.as_view(),name="detail"),
	]

Meter/Reading/models.py
from django.db import models
import datetime
from django.utils import timezone

class Meter(models.Model):
	meter_id=models.CharField(max_length=50,primary_key=True)
	
	def __str__(self):
		return str(self.meter_id)

class Data(models.Model):
	class Meta:
		ordering = ['timestamp']
		# ordering = int['sequence_id']

	meter=models.ForeignKey(Meter,related_name='datas',on_delete=models.CASCADE)
	sequence_id = models.CharField(max_length=50,unique=True)
	timestamp = models.DateTimeField(default=datetime.datetime.now())#timezone.now())#datetime.datetime.now())
	CONNECTION_CHOICES=(('Connected','Connected'),('Disconnected','Disconnected'))
	connection_status = models.CharField(max_length=15,choices=CONNECTION_CHOICES)

	def __str__(self):
		return str(self.meter) + ' - ' + str(self.sequence_id)+ ' - ' + str(self.timestamp)+ ' - ' + str(self.connection_status)

Meter/Reading/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic import View
from .models import Meter,Data

# #RESTAPI
from .serializers import DataSerializer,MeterSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status,viewsets
from rest_framework.permissions import IsAuthenticated,IsAdminUser,AllowAny

class DataViewSet(viewsets.ModelViewSet):
	
	queryset=Data.objects.all()
	serializer_class=DataSerializer
	# permission_classes = [AllowAny]

	def get_permissions(self):
		print ("self.action :",self.action)
		if self.action == 'list':					#list all waterparks
			permission_classes = [AllowAny]
		elif self.action == 'create':				#create a new waterpark
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'retrieve':				#list a single waterpark
			permission_classes = [AllowAny]
		elif self.action == 'update':				#update a waterpark but have to send all the data
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'partial_update':		#update a waterpark but can send single data
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'destroy':				#delete a waterpark
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'hello':
			permission_classes = [AllowAny]
		else:
			permission_classes = [AllowAny]
		return [permission() for permission in permission_classes]

class MeterViewSet(viewsets.ModelViewSet):
	serializer_class = MeterSerializer
	queryset = Meter.objects.all()
	def get_permissions(self):
		print ("self.action :",self.action)
		if self.action == 'list':					#list all waterparks
			permission_classes = [AllowAny]
		elif self.action == 'create':				#create a new waterpark
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'retrieve':				#list a single waterpark
			permission_classes = [AllowAny]
		elif self.action == 'update':				#update a waterpark but have to send all the data
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'partial_update':		#update a waterpark but can send single data
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'destroy':				#delete a waterpark
			permission_classes = [AllowAny]
			# permission_classes = [IsAdminUser]
		elif self.action == 'hello':
			permission_classes = [AllowAny]
		else:
			permission_classes = [AllowAny]
		return [permission() for permission in permission_classes]

class IndexView(generic.ListView):
	template_name="Reading/index.html"
	context_object_name="reading_list"

	def get_queryset(self):
		return Meter.objects.order_by('meter_id')

class DetailView(generic.DetailView):
	model=Meter
	template_name="Reading/detail.html"
	context_object_name="meterid"

Meter/Reading/templates/Reading/detail.html
{% if meterid %}
<div class="row">
    <div class="col-sm-12">
        <h3>Table View</h3>
    </div>
    <div class="col-sm-3 col-md-3 col-lg-3">
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Meter ID</th>
                            <th scope="col">Sequence ID</th>
                            <th scope="col">TimeStamp</th>
                            <th scope="col">Connection Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for x in meterid.datas.all %}
                            <tr>
                                <td scope="row">{{ meterid }}</td>
                                <td>{{ x.sequence_id }}</td>
                                <td>{{ x.timestamp }}</td>
                                <td>{{ x.connection_status }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}
</div>

Meter/Reading/templates/Reading/index.html
{% if reading_list %}
        <div class="row">
            <!-- <div class="col-sm-12">
                <h3>Table View</h3>
            </div> -->
            <div class="col-sm-4 col-md-4 col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Meter ID</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for r in reading_list %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'meter:detail' r.meter_id %}">{{ r.meter_id }}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}